services:

  sparkling-redis:
    container_name: sparkling-redis
    hostname: sparkling-redis
    image: redis:7.4-bookworm
    restart: on-failure
    command: redis-server --save 300 100 --loglevel warning
    volumes: 
      - redis-volume:/data
    networks:
      - sparkling-bridge

  event-engine:
    container_name: event-engine
    image: jonathanarns/sparkling-event-engine:latest
    build: 
      context: ./
      dockerfile: ./event-engine.Dockerfile
    depends_on:
      - sparkling-redis
    networks:
      - sparkling-bridge
    environment:
      - RUST_BACKTRACE=1
    env_file:
      - .env
    restart: on-failure

  web:
    container_name: server
    image: jonathanarns/sparkling-server:latest
    build: 
      context: ./
      dockerfile: ./server.Dockerfile
    depends_on:
      - sparkling-redis
    ports:
      - "80:8080"
    networks:
      - sparkling-bridge
    environment:
      - RUST_BACKTRACE=1
    restart: on-failure

volumes:
  redis-volume:
    driver: local

networks:
  sparkling-bridge:
    driver: bridge
