name: image-build

on:
    push:
      branches: main

jobs:
  docker_build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
      - name: Build and push event engine
        run: |
            docker build --tag jonathanarns/sparkling-event-engine:latest -f event-engine.Dockerfile .
            docker push jonathanarns/sparkling-event-engine:latest

      - name: Build and push server
        run: |
            docker build --file server.Dockerfile --tag jonathanarns/sparkling-server:latest -f server.Dockerfile .
            docker push jonathanarns/sparkling-server:latest
